[[sec-release-0.1]]
== Release 0.1

This is the current master branch and information here is not final. These are changes from the v0.01 tag.

Special thanks to https://github.com/nix-community/home-manager/[home-manager] for this release. Docs/manual generation, the new module evaluation system, and DAG implementation are from them.

[[sec-release-0.1-changelog]]
=== Changelog

https://github.com/jordanisaacs[jordanisaacs]:

* Removed hare language support (lsp/tree-sitter/etc). `vim.lsp.hare` is no longer defined. If you use hare and would like it added back, please file an issue.

* <<opt-vim.startPlugins>> & <<opt-vim.optPlugins>> are now an enum of `string` for options sourced from the flake inputs. Users can still provide vim plugin packages.
+
If you are contributing and adding a new plugin, add the plugin name to `availablePlugins` in https://github.com/jordanisaacs/neovim-flake/blob/20cec032bd74bc3d20ac17ce36cd84786a04fd3e/modules/lib/types-plugin.nix[types-plugin.nix].

* `neovimBuilder` has been removed for configuration. Using an overlay is no longer required. See the manual for the new way to configuration.

* Treesitter grammars are now configurable with <<opt-vim.treesitter.grammars>>. Utilizes the nixpkgs `nvim-treesitter` plugin rather than a custom input in order to take advantage of build support of pinned versions. See https://discourse.nixos.org/t/psa-if-you-are-on-unstable-try-out-nvim-treesitter-withallgrammars/23321?u=snowytrees[discourse] for more information. Packages can be found under the `pkgs.vimPlugins.nvim-treesitter.builtGrammars` attribute. Treesitter grammars for supported languages should be enabled within the module. By default no grammars are installed, thus the following grammars which do not have a language section are not included anymore: comment, toml, make, html, css, graphql, json.

* <<opt-vim.configRC>> and <<opt-vim.luaConfigRC>> are now of type DAG lines. This allows for ordering of the config. Usage is the same is in home-manager's `home.activation` option.
+
[source,nix]
----
vim.luaConfigRC = lib.nvim.dag.entryAnywhere "config here"
----

* Builds are done within the module evaluation. You can override the neovim package used by setting <<opt-build.package>>. There is no more `.neovim` attribute from the configuration function, the output is the package itself. See the manual for accessing the `meta` attributes.

* You can now add your own custom inputs as plugins. See <<opt-build.rawPlugins>>. They can be accessed in <<opt-vim.startPlugins>> & <<opt-vim.optPlugins>>

* Setting aliases has been moved to the `config.build` attribute: <<opt-build.viAlias>> & <<opt-build.vimAlias>>

* Internally, now using the modern https://github.com/NixOS/nixpkgs/blob/c47370e2cc335cb987577ff5fa26c9f29cc7774e/pkgs/applications/editors/neovim/utils.nix#L24[makeNeovimConfig] and https://github.com/NixOS/nixpkgs/blob/c47370e2cc335cb987577ff5fa26c9f29cc7774e/pkgs/applications/editors/neovim/wrapper.nix#L11[wrapNeovimUnstable] for building the final package, <<opt-built.package>>
* A new section has been added for language support: `vim.languages.<language>`. The options <<opt-vim.languages.enableLSP>>, <<opt-vim.languages.enableTreesitter>>, etc. will enable the respective section for all languages that have been enabled.
** All LSP languages have been moved here
** `plantuml` and `markdown` have been moved here
** A new section has been added for `html`. The old `vim.treesitter.autotagHtml` can be found at <<opt-vim.languages.html.treesitter.autotagHtml>>.

* <<opt-vim.git.gitsigns.codeActions>> has been added allowing you to turn on gitsigns codeactions.

* Removed the plugins document in the docs. Was too unwieldy to keep updated.

* `vim.visual.lspkind` has been moved to <<opt-vim.lsp.lspkind.enable>>

* Improved handling of completion formatting. When setting <<opt-vim.autocomplete.sources>>, can also include optional menu mapping. And can provide your own function with <<opt-vim.autocomplete.formatting.format>>.

* For <<opt-vim.visuals.indentBlankline.fillChar>> and <<opt-vim.visuals.indentBlankline.eolChar>> turning them off should use `null` rather than `""` now.

* Add support for extending configurations. See docs for more details.

https://github.com/MoritzBoehme[MoritzBoehme]:

* `catppuccin` theme is now available as a neovim theme <<opt-vim.theme.style>> and lualine theme <<opt-vim.statusline.lualine.theme>>.

https://github.com/antotocar34[antotocar34]:

* Refactored supported theme definitions into a module. This allows any downstream users to define their own themes.

https://github.com/wanderer[wanderer]:

* Added a module for plantuml which utilizes https://github.com/weirongxu/plantuml-previewer.vim[plantuml-previewer] and https://github.com/aklt/plantuml-syntax[plantuml-syntax]. The options <<opt-vim.languages.plantuml.plantumlPackage>> and <<opt-vim.languages.plantuml.javaPackage>> can be used to configure which version of the corresponding packages are used.

https://github.com/MonaMayrhofer[MonaMayrhofer]:

* Add support for https://github.com/Mofiqul/dracula.nvim[Mofiqul/dracula.nvim]
* Add support for https://github.com/dracula/vim[dracula/vim]
* Add support for https://github.com/j-hui/fidget.nvim[fidget.nvim]

https://github.com/volfyd[volfyd]:

* Add support for https://github.com/ellisonleao/gruvbox.nvim
