[[sec-release-0.1]]
== Release 0.1

This is the current master branch and information here is not final. These are changes from the v0.01 tag.

Special thanks to https://github.com/nix-community/home-manager/[home-manager] for this release. Docs/manual generation, the new module evaluation system, and DAG implementation are from them.

[[sec-release-0.1-changelog]]
=== Changelog

https://github.com/jordanisaacs[jordanisaacs]:

* Removed hare language support (lsp/tree-sitter/etc). `vim.lsp.hare` is no longer defined. If you use hare and would like it added back, please file an issue.

* <<opt-vim.startPlugins>> & <<opt-vim.optPlugins>> are now an enum of `string` for options sourced from the flake inputs. Users can still provide vim plugin packages.
+
If you are contributing and adding a new plugin, add the plugin name to `availablePlugins` in https://github.com/jordanisaacs/neovim-flake/blob/20cec032bd74bc3d20ac17ce36cd84786a04fd3e/modules/lib/types-plugin.nix[types-plugin.nix].

* `neovimBuilder` has been removed for configuration. Using an overlay is no longer required. See the manual for the new way to configuration.

* Treesitter grammars are now configurable with <<opt-vim.treesitter.grammars>>. Packages can be found under the `tree-sitter-grammars` namespace on https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=tree-sitter-grammars[nixpkgs].

* <<opt-vim.configRC>> and <<opt-vim.luaConfigRC>> are now of type DAG lines. This allows for ordering of the config. Usage is the same is in home-manager's `home.activation` option.
+
[source,nix]
----
vim.luaConfigRC = lib.nvim.dag.entryAnywhere "config here"
----

https://github.com/MoritzBoehme[MoritzBoehme]:

* `catppuccin` theme is now available as a neovim theme <<opt-vim.theme.style>> and lualine theme <<opt-vim.statusline.lualine.theme>>.

https://github.com/antotocar34[antotocar34]:

* Refactored supported theme definitions into a module. This allows any downstream users to define their own themes.
